import React from 'react';
import {
  Utensils,
  IceCream,
  Home as HomeIcon,
  DollarSign,
  Shirt,
  Smartphone,
  PlusSquare,
  Beer,
  ShoppingCart,
  Hammer,
  Scissors,
  UserCircle,
  Dumbbell,
  PenTool,
  Sparkles,
  Pizza,
  UtensilsCrossed,
  Beef,
  PawPrint,
  Building2,
  Car,
  Gift,
  Briefcase,
  Wrench
} from 'lucide-react';
import { Category } from './types';

export const CATEGORIES: Category[] = [
  { id: 'pizzerias', name: 'Pizzerías', icon: <Pizza className="w-8 h-8" /> },
  { id: 'restaurantes', name: 'Restaurantes', icon: <UtensilsCrossed className="w-8 h-8" /> },
  { id: 'fastfood', name: 'Comida Rápida', icon: <Beef className="w-8 h-8" /> },
  { id: 'beer', name: 'Cervecerías', icon: <Beer className="w-8 h-8" /> },
  { id: 'icecream', name: 'Heladerías', icon: <IceCream className="w-8 h-8" /> },
  { id: 'gastro', name: 'Gastronomías', icon: <Utensils className="w-8 h-8" /> },
  { id: 'markets', name: 'Mercados', icon: <ShoppingCart className="w-8 h-8" /> },
  { id: 'fashion', name: 'Indumentarias', icon: <Shirt className="w-8 h-8" /> },
  { id: 'tech', name: 'Tecnología', icon: <Smartphone className="w-8 h-8" /> },
  { id: 'home', name: 'Hogar', icon: <HomeIcon className="w-8 h-8" /> },
  { id: 'barber', name: 'Barberías', icon: <Scissors className="w-8 h-8" /> },
  { id: 'hair', name: 'Peluquerías', icon: <UserCircle className="w-8 h-8" /> },
  { id: 'gym', name: 'Gimnasios', icon: <Dumbbell className="w-8 h-8" /> },
  { id: 'hardware', name: 'Ferreterías', icon: <Hammer className="w-8 h-8" /> },
  { id: 'pets', name: 'Mascotas', icon: <PawPrint className="w-8 h-8" /> },
  { id: 'tattoo', name: 'Tatuajes', icon: <PenTool className="w-8 h-8" /> },
  { id: 'beauty', name: 'Estéticas', icon: <Sparkles className="w-8 h-8" /> },
  { id: 'inmo', name: 'Inmobiliarias', icon: <Building2 className="w-8 h-8" /> },
  { id: 'auto', name: 'Automotor', icon: <Car className="w-8 h-8" /> },
  { id: 'gifts', name: 'Regalería', icon: <Gift className="w-8 h-8" /> },
  { id: 'finance', name: 'Finanzas', icon: <DollarSign className="w-8 h-8" /> },
  { id: 'servicios', name: 'Servicios y Profesionales', icon: <Briefcase className="w-8 h-8" /> },
  { id: 'automotormotos', name: 'Automotor y Motos', icon: <Wrench className="w-8 h-8" /> },
  { id: 'farmacias', name: 'Farmacias', icon: <PlusSquare className="w-8 h-8" /> },
];