import React from 'react';
import {
    Pizza, UtensilsCrossed, Beef, Beer, IceCream, Utensils,
    ShoppingCart, Shirt, Smartphone, Home as HomeIcon,
    Scissors, UserCircle, Dumbbell, Hammer, PawPrint, PenTool,
    Sparkles, Building2, Car, Gift, DollarSign, Briefcase,
    Wrench, PlusSquare, Shirt as WashIcon, Flower2, Baby,
    Coffee, CookingPot, BookOpen, Music2, Bike, Package,
    Stethoscope, HeartPulse, Bus, Globe, Star,
} from 'lucide-react';

const ICON_MAP: Record<string, React.ReactNode> = {
    Pizza: <Pizza className="w-8 h-8" />,
    UtensilsCrossed: <UtensilsCrossed className="w-8 h-8" />,
    Beef: <Beef className="w-8 h-8" />,
    Beer: <Beer className="w-8 h-8" />,
    IceCream: <IceCream className="w-8 h-8" />,
    Utensils: <Utensils className="w-8 h-8" />,
    ShoppingCart: <ShoppingCart className="w-8 h-8" />,
    Shirt: <Shirt className="w-8 h-8" />,
    Smartphone: <Smartphone className="w-8 h-8" />,
    Home: <HomeIcon className="w-8 h-8" />,
    Scissors: <Scissors className="w-8 h-8" />,
    UserCircle: <UserCircle className="w-8 h-8" />,
    Dumbbell: <Dumbbell className="w-8 h-8" />,
    Hammer: <Hammer className="w-8 h-8" />,
    PawPrint: <PawPrint className="w-8 h-8" />,
    PenTool: <PenTool className="w-8 h-8" />,
    Sparkles: <Sparkles className="w-8 h-8" />,
    Building2: <Building2 className="w-8 h-8" />,
    Car: <Car className="w-8 h-8" />,
    Gift: <Gift className="w-8 h-8" />,
    DollarSign: <DollarSign className="w-8 h-8" />,
    Briefcase: <Briefcase className="w-8 h-8" />,
    Wrench: <Wrench className="w-8 h-8" />,
    PlusSquare: <PlusSquare className="w-8 h-8" />,
    WashIcon: <WashIcon className="w-8 h-8" />,
    Flower2: <Flower2 className="w-8 h-8" />,
    Baby: <Baby className="w-8 h-8" />,
    Coffee: <Coffee className="w-8 h-8" />,
    CookingPot: <CookingPot className="w-8 h-8" />,
    BookOpen: <BookOpen className="w-8 h-8" />,
    Music2: <Music2 className="w-8 h-8" />,
    Bike: <Bike className="w-8 h-8" />,
    Package: <Package className="w-8 h-8" />,
    Stethoscope: <Stethoscope className="w-8 h-8" />,
    HeartPulse: <HeartPulse className="w-8 h-8" />,
    Bus: <Bus className="w-8 h-8" />,
    Globe: <Globe className="w-8 h-8" />,
    Star: <Star className="w-8 h-8" />,
};

// Available icons for the category picker in GlobalConfigPage
export const AVAILABLE_ICONS_FOR_PICKER = [
    { key: 'Pizza', label: 'Pizza' },
    { key: 'UtensilsCrossed', label: 'Restaurant' },
    { key: 'Beef', label: 'Fast Food' },
    { key: 'Beer', label: 'Cervecería' },
    { key: 'IceCream', label: 'Heladería' },
    { key: 'Coffee', label: 'Café' },
    { key: 'CookingPot', label: 'Cocina' },
    { key: 'ShoppingCart', label: 'Mercado' },
    { key: 'Shirt', label: 'Ropa' },
    { key: 'Smartphone', label: 'Tecnología' },
    { key: 'Home', label: 'Hogar' },
    { key: 'Scissors', label: 'Barbería' },
    { key: 'Sparkles', label: 'Estética' },
    { key: 'Dumbbell', label: 'Gimnasio' },
    { key: 'Hammer', label: 'Ferretería' },
    { key: 'PawPrint', label: 'Mascotas' },
    { key: 'Car', label: 'Automotor' },
    { key: 'Wrench', label: 'Motos' },
    { key: 'Building2', label: 'Inmobiliaria' },
    { key: 'Gift', label: 'Regalería' },
    { key: 'DollarSign', label: 'Finanzas' },
    { key: 'Briefcase', label: 'Servicios' },
    { key: 'PlusSquare', label: 'Farmacia' },
    { key: 'Flower2', label: 'Flores' },
    { key: 'Baby', label: 'Bebés' },
    { key: 'BookOpen', label: 'Librería' },
    { key: 'Music2', label: 'Música' },
    { key: 'Bike', label: 'Bicicletas' },
    { key: 'Package', label: 'Depósito' },
    { key: 'Stethoscope', label: 'Salud' },
    { key: 'HeartPulse', label: 'Bienestar' },
    { key: 'Bus', label: 'Transporte' },
    { key: 'Globe', label: 'General' },
    { key: 'Star', label: 'Destacado' },
    { key: 'WashIcon', label: 'Lavandería' },
];

export const resolveIcon = (iconKey: string): React.ReactNode => {
    return ICON_MAP[iconKey] || <Star className="w-8 h-8" />;
};

export default ICON_MAP;
